
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
     - main

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
    networks:
      - main
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    working_dir: /app
    networks:
      - main

networks:
  main:
    driver: bridge

