app:
  port: 8080  # The port on which the application will run
  cors:  # CORS configuration for cross-origin requests
    allow_origins:
      - "*"  # Allowed origins for CORS
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allow_headers:
      - "Content-Type"
      - "Authorization"
    expose_headers:
      - "X-My-Custom-Header"  # Headers exposed to the client
    allow_credentials: true  # Whether to allow credentials (cookies, authorization headers)

  rto: 30s  # Read timeout for the server
  wto: 30s  # Write timeout for the server

repository:

  mongo:  # MongoDB configuration
    users_collection: "users"  # Collection for user data
    books_collection: "books"  # Collection for book data

  redis:
    ttl: 24h

auth:
  jwt:
    access_token_ttl: 24h  # Time-to-live for access tokens
    refresh_token_ttl: 24h  # Time-to-live for refresh tokens

httpClient:
  proxy_url: ""  # URL of the proxy server if used
  timeout: 30s  # Timeout for HTTP client requests